language: csharp
sudo: false

before_install:
 - nuget install SpecFlow -Version 1.9.0
 - nuget install NUnit -Version 2.6.4
 - nuget install NUnit.Runners -Version 2.6.4

script: 
 - xbuild specflow_samples.csproj /t:buildnunitfiles
 - xbuild specflow_samples.csproj /t:compile
 - xbuild specflow_samples.csproj /t:test
