language: csharp
sudo: false
mono: 4.2.0

before_install:
  - nuget install SpecFlow -Version 1.9.0
  - nuget install NUnit -Version 2.6.4
  - nuget install NUnit.Runners -Version 2.6.4
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c specflow.conf --only=features,step_definitions --test-run-id=9941"

script: 
  - xbuild specflow_samples.csproj /t:buildnunitfiles
  - xbuild specflow_samples.csproj /t:compile
  - xbuild specflow_samples.csproj /t:test

after_script:
  - hiptest-publisher -c specflow.conf --push=TestResult.xml --test-run-id=9941
