# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

# pool:
 # vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- script: |
   echo "#! /bin/bash" > $(Pipeline.Workspace)/hiptest-publisher
   echo "docker run --rm --volume=\"$(pwd):/app\" hiptest/hiptest-publisher  \"\$@\"" >> $(Pipeline.Workspace)/hiptest-publisher
   sudo chmod +x $(Pipeline.Workspace)/hiptest-publisher	
  displayName: 'install hiptest-publisher though its docker image as en excutable script'
- script: $(Pipeline.Workspace)/hiptest-publisher -c specflow.conf --token=$(project_token) --test-run-id=$(test_run_id) --only=features
  displayName: 'Regenerate features and fetch UIDs in each scenario included in the test run'
- script: |
    msbuild /t:BuildNUnitFiles
    msbuild
    msbuild /t:Test
  displayName: 'Run tests'
- script: $(Pipeline.Workspace)/hiptest-publisher -c specflow.conf --token=$(project_token) -p "$(Pipeline.Workspace)/target/cuke-results.json" --test-run-id=$(test_run_id)
  displayName: 'Push the test results file to CucumberSudio test run'
