# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project_token: 453614657963279096718948751067446984863199996149362031745
  test_run_id: 434049
  

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.5.8'
    
- script: gem install hiptest-publisher
  displayName: install hiptest-publisher
- script: hiptest-publisher -c specflow.conf --token=$(project_token) --test-run-id=$(test_run_id) --only=features
  displayName: 'Regenerate features and fetch UIDs in each scenario included in the test run'
- script: |
    vsbuild /t:BuildNUnitFiles
    vsbuild
    vsbuild /t:Test
  displayName: 'Run tests'
- script: hiptest-publisher -c specflow.conf --token=$(project_token) -p "$(Pipeline.Workspace)/target/cuke-results.json" --test-run-id=$(test_run_id)
  displayName: 'Push the test results file to CucumberSudio test run'
